country_array = [
	{ "AT" : "German" },
	{ "BE" : "Dutch" },
	{ "BR" : "Brazillian" },
	{ "CA" : "English" },
	{ "CH" : "German" },
	{ "DE" : "German" },
	{ "DK" : "Danish" },
	{ "EU" : "English" },
	{ "FI" : "Finnish" },
	{ "FR" : "French" },
	{ "GB" : "English" },
	{ "GR" : "Greek" },
	{ "HR" : "Croatian" },
	{ "IT" : "Italian" },
	{ "JP" : "Japanese" },
	{ "NL" : "Dutch" },
	{ "NO" : "Norwegian" },
	{ "PH" : "Filipino" },
	{ "PL" : "Polish" },
	{ "RO" : "Romanian" },
	{ "RU" : "Russian" },
	{ "SE" : "Swedish" },
	{ "TW" : "Chinese" },
	{ "UA" : "Ukranian" },
	{ "UK" : "English" },
	{ "US" : "English" },
	]