# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('source_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=30)),
                ('viewers', models.IntegerField()),
                ('name_id', models.CharField(max_length=40)),
                ('name_display', models.CharField(max_length=40)),
                ('source', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('preview', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
