# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='entry',
            field=models.ManyToManyField(blank=True, related_name='game', to='newapp.Entry'),
        ),
    ]
