# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20160416_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_table',
            fields=[
                ('source_id_game', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=40)),
                ('entry', models.ManyToManyField(blank=True, related_name='Game_table', to='newapp.Entry')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
