# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='source_id',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game_table',
            name='source_id_game',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
