# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_auto_20160417_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language_table',
            fields=[
                ('source_id_language', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=30)),
                ('entry', models.ManyToManyField(blank=True, related_name='Language_table', to='newapp.Entry')),
            ],
        ),
    ]
