# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_language_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites_table',
            fields=[
                ('source_id_user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('entry', models.ManyToManyField(blank=True, related_name='Favorites_table', to='newapp.Entry')),
            ],
        ),
    ]
