# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_favorites_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites_table',
            name='source_id',
            field=models.CharField(default='asdf', max_length=80),
            preserve_default=False,
        ),
    ]
