# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_recent_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_table',
            name='timestamp',
        ),
    ]
