# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_remove_recent_table_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_table',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Recent_table',
        ),
    ]
