# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_auto_20160422_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent_table',
            fields=[
                ('source_id_user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=80)),
                ('user', models.CharField(max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entry', models.ManyToManyField(blank=True, related_name='Recent_table', to='newapp.Entry')),
            ],
        ),
    ]
